import type { Document, MemoryTerm } from "@/types";

export const PHASE6_FIXTURE_NOW = "2026-06-16T10:00:00.000Z";

export const PHASE6_DEFAULT_PREFERENCES = {
  interest_tags: JSON.stringify(["Agents", "RAG", "Multimodal"]),
  default_language: "zh",
  summary_length: "short",
  daily_recommend_count: "12",
} as const;

export function createPhase6FixtureDocuments(): Document[] {
  return [
    makeDocument({
      id: "doc-e2e-agent-memory",
      title: "Agent Memory Systems in Production",
      source: "arxiv",
      sourceTag: "arXiv",
      url: "https://example.com/agent-memory",
      publishedAt: "2026-06-16T08:00:00.000Z",
      domainTags: ["Agents", "Memory"],
      modelTags: ["GPT-4"],
      summaryZh: "系统化整理生产环境中的 Agent 记忆架构、压缩策略与回放机制。",
      summaryEn:
        "A practical overview of memory compression architectures for agentic systems in production.",
    }),
    makeDocument({
      id: "doc-e2e-rag-systems",
      title: "RAG Systems for Long-Context Research",
      source: "arxiv",
      sourceTag: "arXiv",
      url: "https://example.com/rag-systems",
      publishedAt: "2026-06-15T18:30:00.000Z",
      domainTags: ["RAG", "Search"],
      modelTags: ["GPT-4.1"],
      summaryZh: "聚焦长上下文研究工作流中的检索增强系统与缓存层设计。",
    }),
    makeDocument({
      id: "doc-e2e-multimodal-ops",
      title: "Multimodal Ops Playbook",
      source: "gpt_blog",
      sourceTag: "GPT Blog",
      typeTag: "blog",
      url: "https://example.com/multimodal-ops",
      publishedAt: "2026-06-15T09:00:00.000Z",
      domainTags: ["Multimodal", "Agents"],
      modelTags: ["GPT-4o"],
      summaryZh: "总结多模态产品上线前的评估、回滚和观测方法。",
    }),
    makeDocument({
      id: "doc-e2e-claude-safety",
      title: "Claude Safety Patterns for Tool Use",
      source: "claude_blog",
      sourceTag: "Claude Blog",
      typeTag: "blog",
      url: "https://example.com/claude-safety",
      publishedAt: "2026-06-14T16:00:00.000Z",
      domainTags: ["Safety", "Agents", "LLM"],
      modelTags: ["Claude 3"],
      summaryZh: "围绕工具调用的防误触、权限边界和降级路径进行总结。",
    }),
    makeDocument({
      id: "doc-e2e-tag-agents-1",
      title: "Agent Planning Benchmarks",
      source: "arxiv",
      sourceTag: "arXiv",
      url: "https://example.com/agent-planning-benchmarks",
      publishedAt: "2026-06-13T11:00:00.000Z",
      domainTags: ["Agents", "Planning"],
      modelTags: ["GPT-4"],
    }),
    makeDocument({
      id: "doc-e2e-tag-agents-2",
      title: "Agent Planning Benchmarks Extended",
      source: "arxiv",
      sourceTag: "arXiv",
      url: "https://example.com/agent-planning-benchmarks-extended",
      publishedAt: "2026-06-12T11:00:00.000Z",
      domainTags: ["Agents", "Planning"],
      modelTags: ["Claude 3"],
    }),
    makeDocument({
      id: "doc-e2e-tag-agents-3",
      title: "Agent Planning with Memory Compression",
      source: "gpt_blog",
      sourceTag: "GPT Blog",
      typeTag: "blog",
      url: "https://example.com/agent-planning-memory",
      publishedAt: "2026-06-11T11:00:00.000Z",
      domainTags: ["Agents", "Planning", "Memory"],
      modelTags: ["GPT-4o"],
    }),
    makeDocument({
      id: "doc-e2e-search-report",
      title: "Prompt Alignment Research Memo",
      source: "claude_blog",
      sourceTag: "Claude Blog",
      typeTag: "blog",
      url: "https://example.com/prompt-alignment-research-memo",
      publishedAt: "2026-06-10T07:30:00.000Z",
      domainTags: ["Prompt Engineering", "Safety"],
      modelTags: ["Claude 3"],
      abstract: "A memo on prompt alignment, eval loops, and deployment safeguards.",
      summaryZh: "包含 Prompt 对齐、评测回路和部署防护的研究备忘。",
    }),
    makeDocument({
      id: "doc-e2e-tag-rag-1",
      title: "RAG Caching Patterns",
      source: "gpt_blog",
      sourceTag: "GPT Blog",
      typeTag: "blog",
      url: "https://example.com/rag-caching-patterns",
      publishedAt: "2026-06-09T10:20:00.000Z",
      domainTags: ["RAG", "Cache"],
      modelTags: ["GPT-4.1"],
    }),
    makeDocument({
      id: "doc-e2e-tag-rag-2",
      title: "RAG Evaluation Loops",
      source: "arxiv",
      sourceTag: "arXiv",
      url: "https://example.com/rag-evaluation-loops",
      publishedAt: "2026-06-08T10:20:00.000Z",
      domainTags: ["RAG", "Evaluation"],
      modelTags: ["GPT-4"],
    }),
    makeDocument({
      id: "doc-e2e-model-gpt4o",
      title: "GPT-4o Research Assistant Patterns",
      source: "gpt_blog",
      sourceTag: "GPT Blog",
      typeTag: "blog",
      url: "https://example.com/gpt4o-research-assistant",
      publishedAt: "2026-06-07T14:45:00.000Z",
      domainTags: ["Agents", "Multimodal"],
      modelTags: ["GPT-4o"],
    }),
    makeDocument({
      id: "doc-e2e-source-openai",
      title: "OpenAI Retrieval Notes",
      source: "gpt_blog",
      sourceTag: "GPT Blog",
      typeTag: "blog",
      url: "https://example.com/openai-retrieval-notes",
      publishedAt: "2026-06-06T13:10:00.000Z",
      domainTags: ["Search"],
      modelTags: ["GPT-4.1"],
    }),
    makeDocument({
      id: "doc-e2e-year-2025",
      title: "2025 Agent Safety Survey",
      source: "arxiv",
      sourceTag: "arXiv",
      url: "https://example.com/2025-agent-safety-survey",
      publishedAt: "2025-12-20T08:00:00.000Z",
      domainTags: ["Safety", "Agents"],
      modelTags: ["GPT-4"],
      yearTag: 2025,
    }),
    ...Array.from({ length: 10 }, (_, index) =>
      makeDocument({
        id: `doc-e2e-agent-archive-${index + 1}`,
        title: `Agent Archive Note ${index + 1}`,
        source: index % 2 === 0 ? "arxiv" : "gpt_blog",
        sourceTag: index % 2 === 0 ? "arXiv" : "GPT Blog",
        typeTag: index % 2 === 0 ? "paper" : "blog",
        url: `https://example.com/agent-archive-${index + 1}`,
        publishedAt: `2026-06-${String(index + 1).padStart(2, "0")}T06:00:00.000Z`,
        domainTags: ["Agents", index % 3 === 0 ? "Planning" : "Memory"],
        modelTags: index % 2 === 0 ? ["GPT-4"] : ["GPT-4o"],
      }),
    ),
  ];
}

export function createPhase6FixtureMemory(): MemoryTerm[] {
  return [
    { category: "domain", term: "Agents", weight: 1.9, source: "digest" },
    { category: "domain", term: "RAG", weight: 1.3, source: "digest" },
    { category: "model", term: "GPT-4o", weight: 1.1, source: "digest" },
    { category: "topic", term: "Multimodal", weight: 0.9, source: "digest" },
  ];
}

function makeDocument(
  overrides: Partial<Document> & Pick<Document, "id" | "title" | "url" | "publishedAt">,
): Document {
  return {
    id: overrides.id,
    title: overrides.title,
    source: overrides.source ?? "arxiv",
    url: overrides.url,
    publishedAt: overrides.publishedAt,
    authors: overrides.authors ?? ["PaperHub Fixtures"],
    abstract:
      overrides.abstract ??
      `${overrides.title} explores local-first paper intelligence workflows, search quality, and release-readiness.`,
    fullTextPath: overrides.fullTextPath,
    language: overrides.language ?? "en",
    domainTags: overrides.domainTags ?? ["Agents"],
    sourceTag: overrides.sourceTag ?? "arXiv",
    typeTag: overrides.typeTag ?? "paper",
    yearTag: overrides.yearTag ?? Number.parseInt(overrides.publishedAt.slice(0, 4), 10),
    modelTags: overrides.modelTags ?? [],
    summaryZh: overrides.summaryZh ?? `${overrides.title} 的中文摘要。`,
    summaryEn: overrides.summaryEn ?? `${overrides.title} summary.`,
    createdAt: PHASE6_FIXTURE_NOW,
    updatedAt: PHASE6_FIXTURE_NOW,
    isSummarized: overrides.isSummarized ?? true,
  };
}
